name: Deploy docs

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true

    - name: Install and Build
      run: |
        cd docs
        conda env create -f environment.yml
        source activate ipyniivue_docs
        python -m ipykernel install --user --name=ipyniivue_docs
        make html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/build/html
        branch: documentation
