name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest # arm64 (Apple Silicon)
          - macos-13  # latest Intel release
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Force numpy < 2 on MacOS Intel
        if: matrix.os == 'macos-13'
        run: pip install 'numpy<2'
      - name: Install 
        run: |
          pip install -e .
          pip install pytest-notebook
          pip install pre-commit
          pre-commit run --all
          pre-commit install
      - name: Test import
        run: |
          python -c "import ipyniivue"
      - name: Test
        run: |
          coverage run -m pytest --nb-test-files
      - name: Upload coverage to codecov (Only do this for the ubuntu-latest job)
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}